Attempt at fix for compilation error
/root/config/zmk/app/src/hid.c: In function 'zmk_hid_masked_modifiers_clear':
/root/config/zmk/app/src/hid.c:162:12: error: 'current' undeclared (first use in this function); did you mean '_current'?
  162 |     return current == GET_MODIFIERS ? 0 : 1;
      |            ^~~~~~~
      |            _current
compilation terminated due to -Wfatal-errors.